# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Football(object):
    def setupUi(self, Football):
        Football.setObjectName("Football")
        Football.resize(841, 369)
        Football.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(Football)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 50, 259, 35))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setStyleSheet("QPushButton#pushButton_3 {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"    background-color: white;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setStyleSheet("QPushButton#pushButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    font: bold 14px;\n"
"    min-width: 7em;\n"
"    padding: 6px;\n"
"    background-color: white;\n"
"}\n"
"QPushButton#pushButton:hover {\n"
"  background-color: #e7e7e7;\n"
"}\n"
"\n"
"\n"
"        \n"
"")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setEnabled(True)
        self.pushButton_6.setGeometry(QtCore.QRect(130, 140, 91, 31))
        self.pushButton_6.setStyleSheet("QPushButton#pushButton_6 {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"    background-color: white;\n"
"}\n"
"QPushButton#pushButton_6:hover {\n"
"  background-color: #e7e7e7;\n"
"}\n"
"\n"
"\n"
"        \n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(540, 140, 0, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(0, 0))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 100, 241, 16))
        self.label_6.setStyleSheet("font: bold 14px;\n"
"color: red;\n"
"  \n"
"")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 90, 271, 31))
        self.label_7.setStyleSheet("font: bold 14px;\n"
"color:rgb(255, 0, 0);\n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setEnabled(True)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 20, 341, 20))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 140, 91, 31))
        self.pushButton_2.setStyleSheet("QPushButton#pushButton_2 {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    font: bold 14px;\n"
"    background-color: white;\n"
"}\n"
"QPushButton#pushButton_2:hover {\n"
"  background-color: #e7e7e7;\n"
"}\n"
"\n"
"\n"
"        \n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(230, 140, 81, 31))
        self.pushButton_4.setStyleSheet("QPushButton#pushButton_4 {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    font: bold 14px;\n"
"    background-color: white;\n"
"}\n"
"QPushButton#pushButton_4:hover {\n"
"  background-color: #e7e7e7;\n"
"}\n"
"\n"
"\n"
"        \n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 100, 341, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setStyleSheet("font: bold 14px;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_4.setStyleSheet("border : 2px solid black;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_2.addWidget(self.lineEdit_4)
        Football.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Football)
        self.statusbar.setObjectName("statusbar")
        Football.setStatusBar(self.statusbar)

        self.retranslateUi(Football)
        QtCore.QMetaObject.connectSlotsByName(Football)

    def retranslateUi(self, Football):
        _translate = QtCore.QCoreApplication.translate
        Football.setWindowTitle(_translate("Football", "MainWindow"))
        self.pushButton_3.setText(_translate("Football", "DATABASE"))
        self.pushButton.setText(_translate("Football", "Connect"))
        self.pushButton_6.setText(_translate("Football", "Live"))
        self.pushButton_2.setText(_translate("Football", "PreMatch"))
        self.pushButton_4.setText(_translate("Football", "Set Pars"))
        self.label_2.setText(_translate("Football", "URL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Football = QtWidgets.QMainWindow()
    ui = Ui_Football()
    ui.setupUi(Football)
    Football.show()
    sys.exit(app.exec_())
